// GENERATED by scripts/oracle.mjs from docs/math-table.html — do not edit.
// Regenerate with `npm run topics:gen`; verify with `npm run topics:check`.

import type { Topic } from "./topics";

export const GENERATED_TOPICS: readonly Topic[] = [
  {
    "id": "facts-mul",
    "name": "Multiplication facts (flashcards)",
    "group": "Math facts",
    "engine": "facts",
    "tagline": "Learn one table at a time, then drill it until it is automatic.",
    "levels": [
      "Twos, fives & tens — the patterns",
      "Threes, fours & sixes",
      "Sevens, eights & nines — the hard ones",
      "Elevens & twelves",
      "Mixed review — everything"
    ]
  },
  {
    "id": "facts-div",
    "name": "Division facts (flashcards)",
    "group": "Math facts",
    "engine": "facts",
    "tagline": "Every division fact is a multiplication fact read backwards.",
    "levels": [
      "Twos, fives & tens — the patterns",
      "Threes, fours & sixes",
      "Sevens, eights & nines — the hard ones",
      "Elevens & twelves",
      "Mixed review — everything"
    ]
  },
  {
    "id": "add",
    "name": "Addition with regrouping",
    "group": "Whole numbers",
    "engine": "grid",
    "tagline": "Line up the places, add each column, and carry what will not fit.",
    "levels": [
      "Two digits",
      "Three digits",
      "Four digits",
      "Five digits"
    ]
  },
  {
    "id": "sub",
    "name": "Subtraction with regrouping",
    "group": "Whole numbers",
    "engine": "grid",
    "tagline": "When the top digit is too small, borrow from next door.",
    "levels": [
      "Two digits",
      "Three digits",
      "Four digits",
      "Across zeros"
    ]
  },
  {
    "id": "mul",
    "name": "Multiplication (multi-digit)",
    "group": "Whole numbers",
    "engine": "grid",
    "tagline": "Break it apart, stack it up, and see why the shortcut works.",
    "levels": [
      "2 digits × 1 digit",
      "3 digits × 1 digit",
      "3 digits × 2 digits",
      "4 digits × 2 digits"
    ]
  },
  {
    "id": "div",
    "name": "Long division",
    "group": "Whole numbers",
    "engine": "grid",
    "tagline": "Divide, multiply, subtract, bring down — one small move at a time.",
    "levels": [
      "2 digits ÷ 1 digit",
      "3 digits ÷ 1 digit",
      "4 digits ÷ 1 digit",
      "÷ 2 digits"
    ]
  },
  {
    "id": "place",
    "name": "Place value & rounding",
    "group": "Whole numbers",
    "engine": "steps",
    "tagline": "Every digit is worth something different. Rounding is just deciding which neighbor is closer.",
    "levels": [
      "4 digits · tens & hundreds",
      "5 digits · up to thousands",
      "6 digits · up to ten-thousands",
      "7 digits · thousands & up"
    ]
  },
  {
    "id": "factors",
    "name": "Factors, GCF & LCM",
    "group": "Whole numbers",
    "engine": "steps",
    "tagline": "Factors divide into a number. Multiples are what it divides into.",
    "levels": [
      "Small numbers",
      "Up to 30",
      "Up to 48",
      "Up to 72"
    ]
  },
  {
    "id": "pemdas",
    "name": "Order of operations",
    "group": "Whole numbers",
    "engine": "steps",
    "tagline": "Parentheses, exponents, then × and ÷, then + and − — left to right within each level.",
    "levels": [
      "Multiply before adding",
      "Parentheses",
      "Longer chains",
      "Exponents"
    ]
  },
  {
    "id": "exponents",
    "name": "Exponents & powers of 10",
    "group": "Whole numbers",
    "engine": "steps",
    "tagline": "An exponent counts how many times you multiply — not what you multiply by.",
    "levels": [
      "Squares & small cubes",
      "Bigger powers",
      "Powers of ten",
      "Mixed"
    ]
  },
  {
    "id": "frac-equiv",
    "name": "Equivalent fractions & simplifying",
    "group": "Fractions",
    "engine": "steps",
    "tagline": "Multiply or divide the top and bottom by the same thing and the fraction stays the same size.",
    "levels": [
      "Small denominators",
      "Up to twelfths",
      "Simplify & fill the blank",
      "Bigger numbers"
    ]
  },
  {
    "id": "frac-mixed",
    "name": "Mixed numbers & improper fractions",
    "group": "Fractions",
    "engine": "steps",
    "tagline": "Two ways of writing the same amount — one counts wholes, one counts pieces.",
    "levels": [
      "Small wholes",
      "Either direction",
      "Bigger numbers",
      "Challenge"
    ]
  },
  {
    "id": "frac-addsub",
    "name": "Add & subtract fractions",
    "group": "Fractions",
    "engine": "steps",
    "tagline": "You can only add pieces that are the same size — so first make them the same size.",
    "levels": [
      "Same denominator",
      "One denominator divides the other",
      "Any denominators",
      "Mixed numbers"
    ]
  },
  {
    "id": "frac-muldiv",
    "name": "Multiply & divide fractions",
    "group": "Fractions",
    "engine": "steps",
    "tagline": "Multiplying is straight across. Dividing is flip the second one, then multiply.",
    "levels": [
      "Multiply simple fractions",
      "Multiply & divide",
      "Bigger numbers",
      "Mixed numbers"
    ]
  },
  {
    "id": "dec-addsub",
    "name": "Add & subtract decimals",
    "group": "Decimals & percents",
    "engine": "grid",
    "tagline": "Line up the decimal points — not the right-hand edges — and everything else is normal.",
    "levels": [
      "Tenths",
      "Hundredths",
      "Different lengths",
      "Across zeros"
    ]
  },
  {
    "id": "dec-muldiv",
    "name": "Multiply & divide decimals",
    "group": "Decimals & percents",
    "engine": "steps",
    "tagline": "Do the whole-number problem first, then work out where the point belongs.",
    "levels": [
      "Times a whole number",
      "Two decimals",
      "Dividing by a decimal",
      "Mixed"
    ]
  },
  {
    "id": "percent",
    "name": "Percents",
    "group": "Decimals & percents",
    "engine": "steps",
    "tagline": "Per cent means \"per hundred\" — every percent is a fraction with 100 on the bottom.",
    "levels": [
      "Friendly percents",
      "Any percent of a number",
      "What percent is it?",
      "Mixed"
    ]
  },
  {
    "id": "ratio",
    "name": "Ratios & unit rates",
    "group": "Ratios & algebra",
    "engine": "steps",
    "tagline": "Find what one of them costs, and every other quantity is easy.",
    "levels": [
      "Simple unit rates",
      "Equivalent ratios",
      "Bigger numbers",
      "Mixed"
    ]
  },
  {
    "id": "integers",
    "name": "Positive & negative numbers",
    "group": "Ratios & algebra",
    "engine": "steps",
    "tagline": "Think of the number line: sign tells you which way, size tells you how far.",
    "levels": [
      "Adding a negative",
      "Subtracting a negative",
      "Both mixed",
      "Multiplying & dividing"
    ]
  },
  {
    "id": "equations",
    "name": "Solving for x",
    "group": "Ratios & algebra",
    "engine": "steps",
    "tagline": "Whatever you do to one side, do to the other. Undo the operations in reverse.",
    "levels": [
      "Add & subtract",
      "Multiply & divide",
      "All one-step types",
      "Two steps"
    ]
  },
  {
    "id": "geometry",
    "name": "Area, perimeter & volume",
    "group": "Geometry",
    "engine": "steps",
    "tagline": "Every formula is really just counting squares — or cubes.",
    "levels": [
      "Rectangles — area",
      "Rectangles — perimeter",
      "Triangles",
      "Parallelograms",
      "Volume of a box",
      "L-shapes",
      "Mixed — every shape"
    ]
  }
] as const;

export const GENERATED_GROUPS: readonly string[] = [
  "Math facts",
  "Whole numbers",
  "Fractions",
  "Decimals & percents",
  "Ratios & algebra",
  "Geometry"
] as const;
